### ISSUE TITLE
the problem of dataset download 

### ISSUE THREAD

**Issue by zsrluminous** [salmank255/smoke-detection#1]
When I open the dataset download link you give, I cannot download because of no permission. The web page prompts that I need permission from the author. I study smoke detection recently and read your paper that is written very well.  I want to download your dataset this paper used to study  smoke detection work. If you see this message, could you send the dataset to my mailbox, my e-mail address is luminous@stu.xjtu.edu.cn, thank you very much.

**Comment by salmank255** [comment]
Thank you very much for taking interest in our work. I changed the privacy of the dataset you can download it now.
